name: dependabot-auto-merge
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Policy: solo patch/minor (modifica qui se vuoi includere i major o solo security)
      - name: Check policy
        run: |
          t="${{ steps.meta.outputs.update-type }}"
          [ "$t" = "version-update:semver-patch" ] || [ "$t" = "version-update:semver-minor" ] || exit 1

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash

      - name: Merge when ready
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          merge-method: squash
